apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-v3.yml -c -o dubbo-sample
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  ports:
  - name: "8899"
    port: 8899
    targetPort: 8899
  selector:
    io.kompose.service: consumer
status:
  loadBalancer: {}
