apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-v3.yml -c -o dubbo-sample
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8899"
        - name: ZOOKEEPER_SERVER
          value: zookeeper
        image: registry.cn-hangzhou.aliyuncs.com/jingshanlb/dubbo-springboot-consumer:latest
        name: consumer
        ports:
        - containerPort: 8899
        resources: {}
      restartPolicy: Always
status: {}
